name: Surgical engineer

on:
  push:
    branches: [ "main", "develop" ]
  pull_request:
    branches: [ "main", "develop" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout del Repositorio
        uses: actions/checkout@v4

      - name: Configurar Entorno de Desarrollo
        # Aquí eliges la 'action' que corresponda a tu proyecto (ej. setup-node, setup-python, setup-java)
        uses: actions/setup-node@v4
        with:
          node-version: '20' # Cambia esta versión según tu proyecto

      - name: Instalar Dependencias
        # Reemplaza el comando según tu gestor de paquetes (npm, pip, yarn, etc.)
        run: npm ci

      - name: Ejecutar Pruebas
        # Reemplaza el comando para correr tus pruebas (npm test, pytest, mvn test, etc.)
        run: npm test

      - name: Compilar la Aplicación
        # Reemplaza el comando de compilación (npm run build, mvn package, etc.)
        run: npm run build
